### ISSUE TITLE
Something about 3D60 dataset

### ISSUE THREAD

**Issue by haoai-1997** [zhijieshen-bjtu/PanoFormer#2]
Hello, there seems to exist something wrong to use the resolution size of 256x512 for 3D60 dataset. The model only fit the resolution size of 512x1024?

**Comment by zhijieshen-bjtu** [comment]
Hi, when applied to 3D60, please adjust the stride of the input projection as well as turn off the "F.interpolate(x, scale_factor=2, mode='nearest')" in the output projection.

**Comment by haoai-1997** [comment]
Thanks！Good Luck！
